version: "3.8"
services:
  cloudformation:
    build:
      context: ./packages/cloudformation
      dockerfile: Dockerfile
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      HISTFILE: /root/.history/bash
    volumes:
      - ${HOME}/dotfiles/.history:/root/.history:delegated
      - ./packages/cloudformation:/var/task:delegated
      - ./.env:/var/task/.base_env:delegated
      - ./config:/var/task/base_config:delegated
      - ./package.json:/var/task/base_package.json:delegated
      - cloudformation-node_modules:/var/task/node_modules

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      HISTFILE: /root/.history/bash
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
    volumes:
      - ${HOME}/dotfiles/.history:/root/.history:delegated
      - ./packages/frontend:/var/task:delegated
      - ./.env:/var/task/.base_env:delegated
      - ./config:/var/task/base_config:delegated
      - ./package.json:/var/task/base_package.json:delegated
      - frontend-node_modules:/var/task/node_modules

  lambda:
    build:
      context: ./packages/lambda
      dockerfile: Dockerfile
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      HISTFILE: /root/.history/bash
    volumes:
      - ${HOME}/dotfiles/.history:/root/.history:delegated
      - ./packages/lambda:/var/task:delegated
      - ./.env:/var/task/.base_env:delegated
      - ./config:/var/task/base_config:delegated
      - ./package.json:/var/task/base_package.json:delegated
      - lambda-node_modules:/var/task/node_modules

volumes:
  cloudformation-node_modules:
  frontend-node_modules:
  lambda-node_modules:
