---

  #====================================================================================================
  # AWS CloudFormation template for creating client VPN security group rules for Givesource
  #====================================================================================================

  AWSTemplateFormatVersion: 2010-09-09
  Description: Creates client VPN security group rules for Givesource

  #==================================================
  # Metadata
  #==================================================
  Metadata:

    AWS::CloudFormation::Interface:

      ParameterGroups:
        - Label:
            default: Setup
          Parameters:
            - RdsSecurityGroupId

      ParameterLabels:
        StackName:
          default: Security group ID

  #==================================================
  # Parameters
  #==================================================
  Parameters:

    RdsSecurityGroupId:
      Description: ID of the RDS security group to add VPN access to
      Type: 'AWS::EC2::SecurityGroup::Id'

  #==================================================
  # Resources
  #==================================================
  Resources:

    RdsSecurityGroupVpnIngress:
      Type: 'AWS::EC2::SecurityGroupIngress'
      Properties:
        Description: All traffic from the client VPN endpoint to RDS
        GroupId: !Ref RdsSecurityGroupId
        FromPort: 3306
        IpProtocol: tcp
        SourceSecurityGroupId: !ImportValue vpn-security-group # imported from engineering-devops/aws/cloudformation/internal-applications/vpn.yml
        ToPort: 3306
