/*
 * Copyright 2018 Firespring, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

exports.TYPE_COLLECTION = 'COLLECTION';
exports.TYPE_FILE = 'FILE';
exports.TYPE_LINK = 'LINK';
exports.TYPE_OPTION = 'OPTION';
exports.TYPE_RICH_TEXT = 'RICH_TEXT';
exports.TYPE_TEXT = 'TEXT';

// About Us Page
exports.CONTENT_ABOUT_TEXT = 'ABOUT_TEXT';

// Cart Page
exports.CONTENT_CART_CHECKOUT_TEXT = 'CART_CHECKOUT_TEXT';
exports.CONTENT_CART_RESPONSE_TEXT = 'CART_RESPONSE_TEXT';

// Contact Us Page
exports.CONTENT_CONTACT_FORM_TEXT = 'CONTACT_FORM_TEXT';
exports.CONTENT_CONTACT_RESPONSE_TEXT = 'CONTACT_RESPONSE_TEXT';

// FAQ Page
exports.CONTENT_FAQ_LIST = 'FAQ_LIST';
exports.CONTENT_FAQ_LIST_ITEM_QUESTION = 'FAQ_LIST_ITEM_QUESTION';
exports.CONTENT_FAQ_LIST_ITEM_ANSWER = 'FAQ_LIST_ITEM_ANSWER';

// Homepage Contents
exports.CONTENT_HOMEPAGE_TITLE = 'HOMEPAGE_TITLE';
exports.CONTENT_HOMEPAGE_MASTHEAD_TEXT = 'HOMEPAGE_MASTHEAD_TEXT';
exports.CONTENT_HOMEPAGE_MAIN_TEXT = 'HOMEPAGE_MAIN_TEXT';
exports.CONTENT_HOMEPAGE_POST_EVENT_TEXT = 'HOMEPAGE_POST_EVENT_TEXT';

exports.CONTENT_HOMEPAGE_REGISTER_BUTTON = 'HOMEPAGE_REGISTER_BUTTON';
exports.CONTENT_HOMEPAGE_REGISTER_DETAILS = 'HOMEPAGE_REGISTER_DETAILS';

exports.CONTENT_HOMEPAGE_MATCH_IS_ENABLED = 'HOMEPAGE_MATCH_IS_ENABLED';
exports.CONTENT_HOMEPAGE_MATCH_BUTTON = 'HOMEPAGE_MATCH_BUTTON';
exports.CONTENT_HOMEPAGE_MATCH_DETAILS = 'HOMEPAGE_MATCH_DETAILS';

// Terms Page
exports.CONTENT_TERMS_TEXT = 'TERMS_TEXT';

// Toolkit Page
exports.CONTENT_TOOLKIT_RESOURCE_LIST = 'TOOLKIT_RESOURCE_LIST';
exports.CONTENT_TOOLKIT_RESOURCE_LIST_ITEM_TITLE = 'TOOLKIT_RESOURCE_LIST_ITEM_TITLE';
exports.CONTENT_TOOLKIT_RESOURCE_LIST_ITEM_DESCRIPTION = 'TOOLKIT_RESOURCE_LIST_ITEM_DESCRIPTION';
exports.CONTENT_TOOLKIT_RESOURCE_LIST_ITEM_TYPE = 'TOOLKIT_RESOURCE_LIST_ITEM_TYPE';
exports.CONTENT_TOOLKIT_RESOURCE_LIST_ITEM_FILE = 'TOOLKIT_RESOURCE_LIST_ITEM_FILE';
exports.CONTENT_TOOLKIT_RESOURCE_LIST_ITEM_LINK = 'TOOLKIT_RESOURCE_LIST_ITEM_LINK';

exports.CONTENT_TOOLKIT_LEADING_TEXT = 'TOOLKIT_LEADING_TEXT';
exports.CONTENT_TOOLKIT_ADDITIONAL_TEXT = 'TOOLKIT_ADDITIONAL_TEXT';