const dayjs = require('dayjs')
const utc = require('dayjs/plugin/utc')
const timezonePlugin = require('dayjs/plugin/timezone')
const customParseFormat = require('dayjs/plugin/customParseFormat')
const dayOfYear = require('dayjs/plugin/dayOfYear')
const advancedFormat = require('dayjs/plugin/advancedFormat')
const weekday = require('dayjs/plugin/weekday')
const localeData = require('dayjs/plugin/localeData')
const isBetween = require('dayjs/plugin/isBetween')

dayjs.extend(utc)
dayjs.extend(timezonePlugin)
dayjs.extend(customParseFormat)
dayjs.extend(dayOfYear)
dayjs.extend(advancedFormat)
dayjs.extend(weekday)
dayjs.extend(localeData)
dayjs.extend(isBetween)

module.exports = dayjs
