/*
 * Copyright 2019 Firespring, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

exports.SETTING_ACCENT_COLOR = 'ACCENT_COLOR';
exports.SETTING_ADMIN_URL = 'ADMIN_URL';
exports.SETTING_API_URL = 'API_URL';
exports.SETTING_CONTACT_PHONE = 'CONTACT_PHONE';
exports.SETTING_CUSTOM_PAGES = 'CUSTOM_PAGES';
exports.SETTING_DATE_DONATIONS_END = 'DATE_DONATIONS_END';
exports.SETTING_DATE_DONATIONS_START = 'DATE_DONATIONS_START';
exports.SETTING_DATE_EVENT_END = 'DATE_EVENT_END';
exports.SETTING_DATE_EVENT_START = 'DATE_EVENT_START';
exports.SETTING_DATE_REGISTRATIONS_END = 'DATE_REGISTRATIONS_END';
exports.SETTING_DATE_REGISTRATIONS_START = 'DATE_REGISTRATIONS_START';
exports.SETTING_EVENT_LOGO = 'EVENT_LOGO';
exports.SETTING_EVENT_TIMEZONE = 'EVENT_TIMEZONE';
exports.SETTING_EVENT_TITLE = 'EVENT_TITLE';
exports.SETTING_EVENT_URL = 'EVENT_URL';
exports.SETTING_FAVICON = 'FAVICON';
exports.SETTING_FOUNDATION_LOGO = 'FOUNDATION_LOGO';
exports.SETTING_FOUNDATION_URL = 'FOUNDATION_URL';
exports.SETTING_GOOGLE_ANALYTICS_TRACKING_ID = 'GOOGLE_ANALYTICS_TRACKING_ID';
exports.SETTING_MASTHEAD_IMAGE = 'MASTHEAD_IMAGE';
exports.SETTING_MATCH_FUND_NONPROFIT_UUID = 'MATCH_FUND_NONPROFIT_UUID';
exports.SETTING_OFFLINE_TRANSACTION_FEE_FLAT_RATE = 'OFFLINE_TRANSACTION_FEE_FLAT_RATE';
exports.SETTING_OFFLINE_TRANSACTION_FEE_PERCENTAGE = 'OFFLINE_TRANSACTION_FEE_PERCENTAGE';
exports.SETTING_PAGE_ABOUT_ENABLED = 'PAGE_ABOUT_ENABLED';
exports.SETTING_PAGE_FAQ_ENABLED = 'PAGE_FAQ_ENABLED';
exports.SETTING_PAGE_TERMS_ENABLED = 'PAGE_TERMS_ENABLED';
exports.SETTING_PAGE_TOOLKIT_ENABLED = 'PAGE_TOOLKIT_ENABLED';
exports.SETTING_PAYMENT_GATEWAY_TRANSACTION_FEE_FLAT_RATE = 'PAYMENT_GATEWAY_TRANSACTION_FEE_FLAT_RATE';
exports.SETTING_PAYMENT_GATEWAY_TRANSACTION_FEE_PERCENTAGE = 'PAYMENT_GATEWAY_TRANSACTION_FEE_PERCENTAGE';
exports.SETTING_SENDER_EMAIL = 'SENDER_EMAIL';
exports.SETTING_SOCIAL_SHARING_DESCRIPTION = 'SOCIAL_SHARING_DESCRIPTION';
exports.SETTING_SOCIAL_SHARING_IMAGE = 'SOCIAL_SHARING_IMAGE';
exports.SETTING_TEST_PAYMENTS_DISPLAY = 'TEST_PAYMENTS_DISPLAY';
exports.SETTING_UPLOADS_CLOUD_FRONT_URL = 'UPLOADS_CLOUD_FRONT_URL';