/*
 * Copyright (C) 2018  Firespring
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

exports.SETTING_ACCENT_COLOR = 'ACCENT_COLOR';
exports.SETTING_ADMIN_URL = 'ADMIN_URL';
exports.SETTING_API_URL = 'API_URL';
exports.SETTING_CONTACT_PHONE = 'CONTACT_PHONE';
exports.SETTING_DATE_DONATIONS_END = 'DATE_DONATIONS_END';
exports.SETTING_DATE_DONATIONS_START = 'DATE_DONATIONS_START';
exports.SETTING_DATE_EVENT = 'DATE_EVENT';
exports.SETTING_DATE_REGISTRATIONS_END = 'DATE_REGISTRATIONS_END';
exports.SETTING_DATE_REGISTRATIONS_START = 'DATE_REGISTRATIONS_START';
exports.SETTING_EVENT_LOGO = 'EVENT_LOGO';
exports.SETTING_EVENT_TIMEZONE = 'EVENT_TIMEZONE';
exports.SETTING_EVENT_TITLE = 'EVENT_TITLE';
exports.SETTING_EVENT_URL = 'EVENT_URL';
exports.SETTING_FAVICON = 'FAVICON';
exports.SETTING_FOUNDATION_LOGO = 'FOUNDATION_LOGO';
exports.SETTING_FOUNDATION_URL = 'FOUNDATION_URL';
exports.SETTING_GOOGLE_ANALYTICS_TRACKING_ID = 'GOOGLE_ANALYTICS_TRACKING_ID';
exports.SETTING_MASTHEAD_IMAGE = 'MASTHEAD_IMAGE';
exports.SETTING_MATCH_FUND_NONPROFIT_UUID = 'MATCH_FUND_NONPROFIT_UUID';
exports.SETTING_OOFFLINE_TRANSACTION_FEE_FLAT_RATE = 'OFFLINE_TRANSACTION_FEE_FLAT_RATE';
exports.SETTING_OFFLINE_TRANSACTION_FEE_PERCENTAGE = 'OFFLINE_TRANSACTION_FEE_PERCENTAGE';
exports.SETTING_PAGE_ABOUT_ENABLED = 'PAGE_ABOUT_ENABLED';
exports.SETTING_PAGE_FAQ_ENABLED = 'PAGE_FAQ_ENABLED';
exports.SETTING_PAGE_TERMS_ENABLED = 'PAGE_TERMS_ENABLED';
exports.SETTING_PAGE_TOOLKIT_ENABLED = 'PAGE_TOOLKIT_ENABLED';
exports.SETTING_PUBLIC_INDEX_TEMPLATE = 'PUBLIC_INDEX_TEMPLATE';
exports.SETTING_SOCIAL_SHARING_DESCRIPTION = 'SOCIAL_SHARING_DESCRIPTION';
exports.SETTING_SOCIAL_SHARING_IMAGE = 'SOCIAL_SHARING_IMAGE';
exports.SETTING_UPLOADS_CLOUD_FRONT_URL = 'UPLOADS_CLOUD_FRONT_URL';