---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS API Gateway Deployment resources for Givesource(R)
Parameters:

  RestApi:
    Type: String

Resources:

  ApiProdDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi

  ApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      CacheClusterEnabled: true
      CacheClusterSize: 0.5
      DeploymentId: !Ref ApiProdDeployment
      RestApiId: !Ref RestApi
      StageName: "prod"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          CacheDataEncrypted: true
          CacheTtlInSeconds: 0
          CachingEnabled: true
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 10000
        - ResourcePath: "/contents"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true
        - ResourcePath: "/donations"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/files"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true
        - ResourcePath: "/files/download/{file_id}"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true
        - ResourcePath: "/metrics"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/nonprofits"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/nonprofits/pages/{slug}"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/nonprofits/search"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/nonprofits/{nonprofit_id}"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 60
          CachingEnabled: true
        - ResourcePath: "/settings"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true
        - ResourcePath: "/sponsor-tiers"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true
        - ResourcePath: "/sponsor-tiers/{sponsor_tier_id}/sponsors"
          HttpMethod: GET
          CacheDataEncrypted: true
          CacheTtlInSeconds: 300
          CachingEnabled: true