---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS API Gateway Deployment resources for Givesource(R)
Parameters:

  RestApi:
    Type: String

Resources:
  ApiGatewayLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayLogRole.Arn

  ApiProdDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi

  ApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      CacheClusterEnabled: true
      CacheClusterSize: 0.5
      DeploymentId: !Ref ApiProdDeployment
      RestApiId: !Ref RestApi
      StageName: "prod"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 0
          CachingEnabled: false
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 10000
        - ResourcePath: "/agreements"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/contents"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 300
          CachingEnabled: false
        - ResourcePath: "/donations"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/files"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 300
          CachingEnabled: false
        - ResourcePath: "/files/download/{file_id}"
          HttpMethod: GET
          LoggingLevel: INFO
          DataTraceEnabled: true
          CachingEnabled: false
        - ResourcePath: "/metrics"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/nonprofits"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/nonprofits/pages/{slug}"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/nonprofits/search"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/nonprofits/{nonprofit_id}"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 60
          CachingEnabled: false
        - ResourcePath: "/settings"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 300
          CachingEnabled: false
        - ResourcePath: "/sponsor-tiers"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 300
          CachingEnabled: false
        - ResourcePath: "/sponsor-tiers/{sponsor_tier_id}/sponsors"
          HttpMethod: GET
#          CacheDataEncrypted: true
#          CacheTtlInSeconds: 300
          CachingEnabled: false
    DependsOn: ApiGatewayAccount
