---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS S3 resources for Givesource(R)
Parameters:

  AdminPagesCNAMEs:
    Type: CommaDelimitedList

  AdminPagesSSLCertificateArn:
    Type: String

  PublicPagesCNAMEs:
    Type: CommaDelimitedList

  PublicPagesSSLCertificateArn:
    Type: String

  StackName:
    Type: String

  LambdaDefaultRuntime:
    Type: String

Conditions:

  HasAdminPagesCNAMEs: !Not [!Equals ["", !Join ["", !Ref AdminPagesCNAMEs ] ] ]

  HasAdminPagesSSLCertificateArn: !Not [!Equals ["", !Ref AdminPagesSSLCertificateArn]]

  HasPublicPagesCNAMEs: !Not [!Equals ["", !Join ["", !Ref PublicPagesCNAMEs ] ] ]

  HasPublicPagesSSLCertificateArn: !Not [!Equals ["", !Ref PublicPagesSSLCertificateArn]]

Resources:

  # AWS S3 Resources

  AdminPagesS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html

  AdminPagesS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AdminPagesS3
      PolicyDocument:
        Statement:
        - Sid: allow-ssl-requests-only
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${AdminPagesS3}/*
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: allow-cloudfront-access
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
          Action: s3:Get*
          Resource: !Sub arn:aws:s3:::${AdminPagesS3}/*

  PublicPagesS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html

  PublicPagesS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicPagesS3
      PolicyDocument:
        Statement:
        - Sid: allow-ssl-requests-only
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${PublicPagesS3}/*
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: allow-cloudfront-access
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
          Action: s3:Get*
          Resource: !Sub arn:aws:s3:::${PublicPagesS3}/*

  UploadsS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 3600
      WebsiteConfiguration:
        IndexDocument: index.html

  UploadsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadsS3
      PolicyDocument:
        Statement:
        - Sid: allow-ssl-requests-only
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${UploadsS3}/*
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: allow-cloudfront-access
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
          Action: s3:Get*
          Resource: !Sub arn:aws:s3:::${UploadsS3}/*

  Reports:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !ImportValue AccessLoggingBucket
        LogFilePrefix: !Sub reports-${StackName}/

  ReportsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Reports
      PolicyDocument:
        Statement:
        - Sid: allow-ssl-requests-only
          Effect: Deny
          Principal: '*'
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${Reports}/*
          Condition:
            Bool:
              aws:SecureTransport: false

  GivesourceCache:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
      WebsiteConfiguration:
        IndexDocument: index.html

  GivesourceCacheBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GivesourceCache
      PolicyDocument:
        Statement:
        - Sid: allow-ssl-requests-only
          Effect: Deny
          Principal: "*"
          Action: s3:*
          Resource: !Sub arn:aws:s3:::${GivesourceCache}/*
          Condition:
            Bool:
              aws:SecureTransport: false
        - Sid: allow-cloudfront-access
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
          Action: s3:Get*
          Resource: !Sub arn:aws:s3:::${GivesourceCache}/*

  # AWS CloudFront Resources

  AdminPagesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If [HasAdminPagesCNAMEs, !Ref AdminPagesCNAMEs, !Ref "AWS::NoValue"]
        Origins:
          - DomainName: !GetAtt AdminPagesS3.DomainName
            Id: !Ref AdminPagesS3
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOAI]]
        Enabled: true
        Comment: !Sub Distribution for Givesource(R) ${StackName} admin pages S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: !Ref AdminPagesS3
          MaxTTL: 86400
          MinTTL: 0
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          ResponseHeadersPolicyId: !ImportValue global-short-lived-caching-header-policy
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !If [HasAdminPagesSSLCertificateArn, !Ref AdminPagesSSLCertificateArn, !Ref "AWS::NoValue"]
          CloudFrontDefaultCertificate: !If [HasAdminPagesSSLCertificateArn, !Ref "AWS::NoValue", true]
          MinimumProtocolVersion: !If [HasAdminPagesSSLCertificateArn, "TLSv1.2_2021", !Ref "AWS::NoValue"]
          SslSupportMethod: !If [HasAdminPagesSSLCertificateArn, "sni-only", !Ref "AWS::NoValue"]
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        WebACLId: !ImportValue givesource-default-cloudfront-waf-arn
    DependsOn: AdminPagesS3

  PublicPagesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !If [HasPublicPagesCNAMEs, !Ref PublicPagesCNAMEs, !Ref "AWS::NoValue"]
        Origins:
        - Id: !Ref PublicPagesS3
          DomainName: !GetAtt PublicPagesS3.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOAI]]
        Enabled: true
        Comment: !Sub Distribution for Givesource(R) ${StackName} public pages S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
            Headers:
              - User-Agent
          TargetOriginId: !Ref PublicPagesS3
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref GeneratePublicPagesHtmlVersion{{lambdaEdgeGenPubPagesHash}}
          MaxTTL: 86400
          MinTTL: 0
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          ResponseHeadersPolicyId: !ImportValue global-short-lived-caching-header-policy
        CacheBehaviors:
          - PathPattern: assets/*
            DefaultTTL: 31536000 # 365 days
            Compress: true
            ViewerProtocolPolicy: redirect-to-https
            TargetOriginId: !Ref PublicPagesS3
            ResponseHeadersPolicyId: !ImportValue global-long-lived-caching-header-policy
            ForwardedValues:
              QueryString: false
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !If [HasPublicPagesSSLCertificateArn, !Ref PublicPagesSSLCertificateArn, !Ref "AWS::NoValue"]
          CloudFrontDefaultCertificate: !If [HasPublicPagesSSLCertificateArn, !Ref "AWS::NoValue", true]
          MinimumProtocolVersion: !If [HasPublicPagesSSLCertificateArn, "TLSv1.2_2021", !Ref "AWS::NoValue"]
          SslSupportMethod: !If [HasPublicPagesSSLCertificateArn, "sni-only", !Ref "AWS::NoValue"]
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        WebACLId: !ImportValue givesource-default-cloudfront-waf-arn
    DependsOn: PublicPagesS3

  LambdaEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
      - PolicyName: CloudWatchLogs
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource:
                - arn:aws:logs:*:*:*
      - PolicyName: SSMGetParameter
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
              - ssm:GetParameter
              Resource:
                - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${StackName}-GeneratePublicPagesHtml/config
      - PolicyName: S3Access
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: s3:ListBucket
              Resource:
                - !GetAtt GivesourceCache.Arn
            - Effect: Allow
              Action:
                - s3:Get*
              Resource:
                - !Sub ${GivesourceCache.Arn}/*

  # Lambda@Edge does not support dead letter queues
  GeneratePublicPagesHtmlFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${StackName}-GeneratePublicPagesHtml
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/GeneratePublicPagesHtml.zip
      Role: !GetAtt LambdaEdgeRole.Arn
      Runtime: !Ref LambdaDefaultRuntime
      Handler: "index.handle"
      MemorySize: 128
      Timeout: 5

  # NOTE: A new version resource needs created whenever the public html function is updated.
  #       This does not happen automatically - you have to change the GeneratePublicPagesHtmlVersion
  #       resource name to something else. We are using the hash of the function source as part of the
  #       resource name in order to accomplish this.
  GeneratePublicPagesHtmlVersion{{lambdaEdgeGenPubPagesHash}}:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref GeneratePublicPagesHtmlFunction
    DependsOn:
      - GeneratePublicPagesHtmlFunction

  UploadsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt UploadsS3.DomainName
          Id: !Ref UploadsS3
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOAI]]
        Enabled: true
        Comment: !Sub Distribution for Givesource(R) ${StackName} uploads S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: !Ref UploadsS3
          DefaultTTL: 600
          MaxTTL: 86400
          MinTTL: 0
          Compress: true
          ResponseHeadersPolicyId: !ImportValue global-medium-caching-header-policy
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        WebACLId: !ImportValue givesource-default-cloudfront-waf-arn
    DependsOn: UploadsS3

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref UploadsS3

  CachingDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt GivesourceCache.DomainName
          Id: !Ref GivesourceCache
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOAI]]
        Enabled: true
        Comment: !Sub Distribution for Givesource(R) ${StackName} caching S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: !Ref GivesourceCache
          MaxTTL: 86400
          MinTTL: 0
          Compress: true
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        WebACLId: !ImportValue givesource-default-cloudfront-waf-arn
    DependsOn: GivesourceCache


Outputs:

  AdminPagesCloudFrontDistribution:
    Value: !Ref AdminPagesDistribution

  AdminPagesCloudFrontDomainName:
    Value: !GetAtt AdminPagesDistribution.DomainName

  AdminPagesCloudFrontUrl:
    Value: !Sub |-
      https://${AdminPagesDistribution.DomainName}

  AdminPagesS3:
    Value: !Ref AdminPagesS3

  AdminPagesS3BucketUrl:
    Value: !GetAtt AdminPagesS3.WebsiteURL

  PublicPagesCloudFrontDistribution:
    Value: !Ref PublicPagesDistribution

  PublicPagesCloudFrontDomainName:
    Value: !GetAtt PublicPagesDistribution.DomainName

  PublicPagesCloudFrontUrl:
    Value: !Sub |-
      https://${PublicPagesDistribution.DomainName}

  PublicPagesS3:
    Value: !Ref PublicPagesS3

  PublicPagesS3BucketUrl:
    Value: !GetAtt PublicPagesS3.WebsiteURL

  UploadsCloudFrontDistribution:
    Value: !Ref UploadsDistribution

  UploadsCloudFrontDomainName:
    Value: !GetAtt UploadsDistribution.DomainName

  UploadsCloudFrontUrl:
    Value: !Sub |-
      https://${UploadsDistribution.DomainName}

  UploadsS3:
    Value: !Ref UploadsS3

  UploadsS3BucketUrl:
    Value: !GetAtt UploadsS3.WebsiteURL

  CachingCloudFrontDistribution:
    Value: !Ref CachingDistribution

  CachingCloudFrontDomainName:
    Value: !GetAtt CachingDistribution.DomainName

  CachingCloudFrontUrl:
    Value: !Sub |-
      https://${CachingDistribution.DomainName}

  GivesourceCache:
    Value: !Ref GivesourceCache

  GivesourceCacheBucketUrl:
    Value: !GetAtt GivesourceCache.WebsiteURL

  Reports:
    Value: !Ref Reports

  ReportsBucketUrl:
    Value: !GetAtt Reports.WebsiteURL
