---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS API Gateway Deployment resources for Givesource
Parameters:

  StackName:
    Type: String

  LambdaRoleArn:
    Type: String

  RestApi:
    Type: String

Resources:

  ApiGatewayDeployFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/ApiGatewayDeploy.zip
      Description: "Deploy the API Gateway"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-ApiGatewayDeploy
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: "prod"

  ApiGatewayDeploy:
    Type: Custom::ApiGatewayDeploy
    Properties:
      ServiceToken: !GetAtt ApiGatewayDeployFunction.Arn
      RestApiId: !Ref RestApi
      StageName: "prod"
      Version: {{version}}
    DependsOn:
      - ApiGatewayDeployFunction
      - ApiDeployment