---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS S3 resources for Givesource
Resources:

  AdminPagesS3:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

  AdminPagesS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AdminPagesS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Principal: "*"
            Resource: !Sub |-
              arn:aws:s3:::${AdminPagesS3}/*

  AdminPagesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              !Select [ 2, !Split [ /, !GetAtt AdminPagesS3.WebsiteURL ] ]
            Id: !Ref AdminPagesS3
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        Comment: Distribution for Givsource admin pages S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          TargetOriginId: !Ref AdminPagesS3
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  PublicPagesS3:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

  PublicPagesS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicPagesS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Principal: "*"
            Resource: !Sub |-
              arn:aws:s3:::${PublicPagesS3}/*

  PublicPagesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              !Select [ 2, !Split [ /, !GetAtt PublicPagesS3.WebsiteURL ] ]
            Id: !Ref PublicPagesS3
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        Comment: Distribution for Givesource public pages S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          TargetOriginId: !Ref PublicPagesS3
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  UploadsS3:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 3600
      WebsiteConfiguration:
        IndexDocument: index.html

  UploadsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadsS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Principal: "*"
            Resource: !Sub |-
              arn:aws:s3:::${UploadsS3}/*

  UploadsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              !Select [ 2, !Split [ /, !GetAtt UploadsS3.WebsiteURL ] ]
            Id: !Ref UploadsS3
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        Comment: Distribution for Givesource uploads S3 bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          DefaultTTL: 0
          TargetOriginId: !Ref UploadsS3
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:

  AdminPagesCloudFrontUrl:
    Value: !Sub |-
      https://${AdminPagesDistribution.DomainName}

  AdminPagesS3:
    Value: !Ref AdminPagesS3

  AdminPagesS3BucketUrl:
    Value: !GetAtt AdminPagesS3.WebsiteURL

  PublicPagesCloudFrontUrl:
    Value: !Sub |-
      https://${PublicPagesDistribution.DomainName}

  PublicPagesS3:
    Value: !Ref PublicPagesS3

  PublicPagesS3BucketUrl:
    Value: !GetAtt PublicPagesS3.WebsiteURL

  UploadsCloudFrontUrl:
    Value: !Sub |-
      https://${UploadsDistribution.DomainName}

  UploadsS3:
    Value: !Ref UploadsS3

  UploadsS3BucketUrl:
    Value: !GetAtt UploadsS3.WebsiteURL