---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS DynamoDB resources for Givesource
Parameters:

  StackName:
    Type: String

Resources:

  ContentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Contents
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: key
        AttributeType: S
      - AttributeName: parentUuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: keyIndex
        KeySchema:
        - AttributeName: key
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: parentUuidIndex
        KeySchema:
        - AttributeName: parentUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  DonationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Donations
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: isDeleted
        AttributeType: N
      - AttributeName: subtotal
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: isDeletedCreatedOnIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: createdOn
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: isDeletedSubtotalIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: subtotal
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: nonprofitUuidCreatedOnIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        - AttributeName: createdOn
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: nonprofitUuidSubtotalIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        - AttributeName: subtotal
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: ContentsTable

  DonorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Donors
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: DonationsTable

  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Files
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    DependsOn: DonorsTable

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Messages
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    DependsOn: FilesTable

  MetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Metrics
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: key
        AttributeType: S
      KeySchema:
      - AttributeName: key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: uuidIndex
        KeySchema:
        - AttributeName: uuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: MessagesTable

  NonprofitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Nonprofits
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: status
        AttributeType: S
      - AttributeName: slug
        AttributeType: S
      - AttributeName: isDeleted
        AttributeType: N
      - AttributeName: donationsSubtotal
        AttributeType: N
      - AttributeName: legalName
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: isDeletedCreatedOnIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: createdOn
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: isDeletedLegalNameIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: legalName
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: statusLegalNameIndex
        KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: legalName
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: statusSubtotalIndex
        KeySchema:
        - AttributeName: status
          KeyType: HASH
        - AttributeName: donationsSubtotal
          KeyType: RANGE
        Projection:
          ProjectionType:   ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: slugIndex
        KeySchema:
        - AttributeName: slug
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: MetricsTable

  NonprofitDonationTiersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-NonprofitDonationTiers
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: NonprofitsTable

  NonprofitSlidesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-NonprofitSlides
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: NonprofitDonationTiersTable

  PaymentTransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-PaymentTransactions
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    DependsOn: NonprofitSlidesTable

  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Reports
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    DependsOn: PaymentTransactionsTable

  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Settings
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: key
        AttributeType: S
      KeySchema:
      - AttributeName: key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: uuidIndex
        KeySchema:
        - AttributeName: uuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: ReportsTable

  SponsorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Sponsors
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: sponsorTierUuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: sponsorTierUuidIndex
        KeySchema:
        - AttributeName: sponsorTierUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: SettingsTable

  SponsorTiersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-SponsorTiers
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: name
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: nameIndex
        KeySchema:
        - AttributeName: name
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: SponsorsTable

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Users
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: cognitoUuid
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: cognitoUuidIndex
        KeySchema:
        - AttributeName: cognitoUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: SponsorTiersTable

Outputs:

  ContentsTable:
    Value: !Ref ContentsTable

  DonationsTable:
    Value: !Ref DonationsTable

  DonorsTable:
    Value: !Ref DonorsTable

  FilesTable:
    Value: !Ref FilesTable

  MessagesTable:
    Value: !Ref MessagesTable

  MetricsTable:
    Value: !Ref MetricsTable

  NonprofitsTable:
    Value: !Ref NonprofitsTable

  NonprofitDonationTiersTable:
    Value: !Ref NonprofitDonationTiersTable

  NonprofitSlidesTable:
    Value: !Ref NonprofitSlidesTable

  PaymentTransactionsTable:
    Value: !Ref PaymentTransactionsTable

  ReportsTable:
    Value: !Ref ReportsTable

  SettingsTable:
    Value: !Ref SettingsTable

  SponsorsTable:
    Value: !Ref SponsorsTable

  SponsorTiersTable:
    Value: !Ref SponsorTiersTable

  UsersTable:
    Value: !Ref UsersTable