---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS API Gateway Deployment resources for Givesource
Parameters:

  RestApi:
    Type: String

Resources:

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: "prod"

  ApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      CacheClusterEnabled: true
      CacheClusterSize: 0.5
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref RestApi
      StageName: "prod"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          CacheDataEncrypted: true
          CacheTtlInSeconds: 0
          CachingEnabled: true
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 10000
        - ResourcePath: "/donations"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/files"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/metrics"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/nonprofits"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/settings"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/sponsor-tiers"
          HttpMethod: GET
          CacheTtlInSeconds: 60
        - ResourcePath: "/sponsor-tiers/{sponsor_tier_uuid}/sponsors"
          HttpMethod: GET
          CacheTtlInSeconds: 60