---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS DynamoDB resources for Givesource
Parameters:

  StackName:
    Type: String

Resources:

  DonationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Donations
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: isDeleted
        AttributeType: N
      - AttributeName: amountInCents
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: paginationCreatedOnIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: createdOn
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: paginationAmountInCentsIndex
        KeySchema:
        - AttributeName: isDeleted
          KeyType: HASH
        - AttributeName: amountInCents
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  DonorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Donors
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: DonationsTable

  FilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Files
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: DonorsTable

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Messages
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: FilesTable

  NonprofitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Nonprofits
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: status
        AttributeType: S
      - AttributeName: slug
        AttributeType: S
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: statusIndex
        KeySchema:
        - AttributeName: status
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: slugIndex
        KeySchema:
        - AttributeName: slug
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: MessagesTable

  NonprofitDonationTiersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-NonprofitDonationTiers
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: NonprofitsTable

  NonprofitSlidesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-NonprofitSlides
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: nonprofitUuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: nonprofitUuidIndex
        KeySchema:
        - AttributeName: nonprofitUuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: NonprofitDonationTiersTable

  PaymentTransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-PaymentTransactions
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: NonprofitSlidesTable

  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Reports
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: PaymentTransactionsTable

  SettingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Settings
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      - AttributeName: key
        AttributeType: S
      KeySchema:
      - AttributeName: key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: uuidIndex
        KeySchema:
        - AttributeName: uuid
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: ReportsTable

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub |-
       ${StackName}-Users
      AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: createdOn
        AttributeType: N
      KeySchema:
      - AttributeName: uuid
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: emailIndex
        KeySchema:
        - AttributeName: email
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: createdOnIndex
        KeySchema:
        - AttributeName: createdOn
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DependsOn: SettingsTable

Outputs:

  DonationsTable:
    Value: !Ref DonationsTable

  DonorsTable:
    Value: !Ref DonorsTable

  FilesTable:
    Value: !Ref FilesTable

  MessagesTable:
    Value: !Ref MessagesTable

  NonprofitsTable:
    Value: !Ref NonprofitsTable

  NonprofitDonationTiersTable:
    Value: !Ref NonprofitDonationTiersTable

  NonprofitSlidesTable:
    Value: !Ref NonprofitSlidesTable

  PaymentTransactionsTable:
    Value: !Ref PaymentTransactionsTable

  ReportsTable:
    Value: !Ref ReportsTable

  SettingsTable:
    Value: !Ref SettingsTable

  UsersTable:
    Value: !Ref UsersTable