---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Custom resources for Givesource
Parameters:

  StackName:
    Type: String

  RestApi:
    Type: String

  LambdaRoleArn:
    Type: String

  DefaultLambdaFunctionTimeout:
    Type: Number

  CognitoSnsCallerRoleArn:
    Type: String

  S3HandleFunctionRoleArn:
    Type: String

  AdminPagesS3:
    Type: String

  AdminPagesCloudFrontUrl:
    Type: String

  PublicPagesS3:
    Type: String

  PublicPagesCloudFrontUrl:
    Type: String

  UploadsS3:
    Type: String

  UploadsCloudFrontUrl:
    Type: String

Resources:

  # Api Gateway Authorizer Lambda Resources

  AuthorizeUsersLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/AuthorizeUsers.zip
      Description: 'Cognito user authorizer'
      Environment:
        Variables:
          REGION: !Sub |-
            ${AWS::Region}
          USER_POOL_ID: !GetAtt CognitoUserPool.UserPoolId
      FunctionName: !Sub |-
        ${StackName}-AuthorizeUsers
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout
    DependsOn: CognitoUserPool

  AuthorizeUsersLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AuthorizeUsersLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/authorizers/${Authorizer}
        - Authorizer: !Ref AuthorizeUsers
    DependsOn:
      - AuthorizeUsersLambdaFunction
      - AuthorizeUsers

  # Api Gateway Authorizers

  AuthorizeUsers:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerUri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function}/invocations
        - Function: !GetAtt AuthorizeUsersLambdaFunction.Arn
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      Name: AuthorizeUsers
      RestApiId: !Ref RestApi
    DependsOn: AuthorizeUsersLambdaFunction

  # Cognito User Pools

  CognitoCreateUserPoolFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CognitoCreateUserPool.zip
      Description: "Create a user pool"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
          COGNITO_CUSTOM_MESSAGE_FUNCTION_ARN: !GetAtt CognitoCustomMessageFunction.Arn
      FunctionName: !Sub |-
        ${StackName}-CognitoCreateUserPool
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout
    DependsOn: CognitoCustomMessageFunction

  CognitoCreateUserPoolClientFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CognitoCreateUserPoolClient.zip
      Description: "Create a user pool client"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CognitoCreateUserPoolClient
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  CognitoCreateUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CognitoCreateUser.zip
      Description: "Create a user"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CognitoCreateUser
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  CognitoCreateUserGroupFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CognitoCreateUserGroup.zip
      Description: "Create a user group"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CognitoCreateUserGroup
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  CognitoCustomMessageFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CognitoCustomMessage.zip
      Description: "Custom user verification message"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
          ADMIN_PAGES_CLOUD_FRONT_URL: !Ref AdminPagesCloudFrontUrl
      FunctionName: !Sub |-
        ${StackName}-CognitoCustomMessage
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  CognitoCustomMessageLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CognitoCustomMessageFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "cognito-idp.amazonaws.com"
      SourceArn: !Sub |-
        arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool.UserPoolId}
    DependsOn:
      - CognitoUserPool
      - CognitoCustomMessageFunction

  # Render Template Lambda Resources

  RenderTemplateLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/RenderTemplate.zip
      Description: "Render a template"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-RenderTemplate
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  # Save Settings Lambda Resources

  SaveSettingsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/SaveSettings.zip
      Description: "Save stack settings"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-SaveSettings
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  # S3 Lambda Resources

  S3PutObjectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/S3PutObject.zip
      Description: "Put an object into an AWS S3 bucket"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-S3PutObject
      Handler: "index.handle"
      Role: !Ref S3HandleFunctionRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  S3SyncObjectsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/S3SyncObjects.zip
      Description: "Sync S3 objects between two AWS S3 buckets"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-S3SyncObjects
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  AdminPagesSettingsJson:
    Type: Custom::S3PutObject
    Properties:
      ServiceToken: !GetAtt S3PutObjectFunction.Arn
      Region: !Sub |-
        ${AWS::Region}
      Bucket: !Ref AdminPagesS3
      Key: "settings.json"
      Body: !Sub |-
        {
          "API_URL": "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
        }
    DependsOn:
      - S3PutObjectFunction
      - CognitoUserPool
      - CognitoUserPoolClient

  AdminPagesDeploy:
    Type: Custom::S3SyncObjects
    Properties:
      ServiceToken: !GetAtt S3SyncObjectsFunction.Arn
      SourceBucket: {{awsReleaseBucket}}
      SourceKey: admin-pages/{{version}}
      DestinationRegion: !Sub |-
        ${AWS::Region}
      DestinationBucket: !Ref AdminPagesS3
    DependsOn: S3SyncObjectsFunction

  PublicPagesSettingsJson:
    Type: Custom::S3PutObject
    Properties:
      ServiceToken: !GetAtt S3PutObjectFunction.Arn
      Region: !Sub |-
        ${AWS::Region}
      Bucket: !Ref PublicPagesS3
      Key: "settings.json"
      Body: !Sub |-
        {
          "API_URL": "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
        }
    DependsOn:
      - S3PutObjectFunction
      - CognitoUserPool
      - CognitoUserPoolClient

  PublicPagesDeploy:
    Type: Custom::S3SyncObjects
    Properties:
      ServiceToken: !GetAtt S3SyncObjectsFunction.Arn
      SourceBucket: {{awsReleaseBucket}}
      SourceKey: public-pages/{{version}}
      DestinationRegion: !Sub |-
        ${AWS::Region}
      DestinationBucket: !Ref PublicPagesS3
    DependsOn: S3SyncObjectsFunction

  CognitoUserPool:
    Type: Custom::CognitoUserPool
    Properties:
      ServiceToken: !GetAtt CognitoCreateUserPoolFunction.Arn
      Region: !Sub |-
        ${AWS::Region}
      PoolName: !Sub |-
        ${StackName}-Users
      AdminPagesUrl: !Ref AdminPagesCloudFrontUrl
      SnsCallerArn: !Ref CognitoSnsCallerRoleArn
    DependsOn: CognitoCreateUserPoolFunction

  CognitoUserPoolClient:
    Type: Custom::CognitoUserPoolClient
    Properties:
      ServiceToken: !GetAtt CognitoCreateUserPoolClientFunction.Arn
      Region: !Sub |-
        ${AWS::Region}
      ClientName: "Browser"
      UserPoolId: !Sub |-
        ${CognitoUserPool.UserPoolId}
    DependsOn:
     - CognitoUserPool
     - CognitoCreateUserPoolClientFunction

  CognitoSuperAdminUserGroup:
    Type: Custom::CognitoSuperAdminUserGroup
    Properties:
      ServiceToken: !GetAtt CognitoCreateUserGroupFunction.Arn
      GroupName: "SuperAdmin"
      UserPoolId: !Sub |-
        ${CognitoUserPool.UserPoolId}
      RoleArn: !Ref LambdaRoleArn
    DependsOn:
      - CognitoUserPool
      - CognitoCreateUserGroupFunction

  CognitoAdminUserGroup:
    Type: Custom::CognitoAdminUserGroup
    Properties:
      ServiceToken: !GetAtt CognitoCreateUserGroupFunction.Arn
      GroupName: "Admin"
      UserPoolId: !Sub |-
        ${CognitoUserPool.UserPoolId}
      RoleArn: !Ref LambdaRoleArn
    DependsOn:
      - CognitoUserPool
      - CognitoCreateUserGroupFunction

  CognitoNonprofitUserGroup:
    Type: Custom::CognitoNonprofitUserGroup
    Properties:
      ServiceToken: !GetAtt CognitoCreateUserGroupFunction.Arn
      GroupName: "Nonprofit"
      UserPoolId: !Sub |-
        ${CognitoUserPool.UserPoolId}
      RoleArn: !Ref LambdaRoleArn
    DependsOn:
      - CognitoUserPool
      - CognitoCreateUserGroupFunction

  SaveInitialStackSettings:
    Type: Custom::Settings
    Properties:
      ServiceToken: !GetAtt SaveSettingsLambdaFunction.Arn
      Settings: !Sub |-
        {
          "API_URL": "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/",
          "ADMIN_PAGES_CLOUDFRONT_URL": "${AdminPagesCloudFrontUrl}",
          "ADMIN_PAGES_S3_BUCKET_NAME": "${AdminPagesS3}",
          "EVENT_URL": "${PublicPagesCloudFrontUrl}",
          "PUBLIC_PAGES_CLOUDFRONT_URL": "${PublicPagesCloudFrontUrl}",
          "PUBLIC_PAGES_S3_BUCKET_NAME": "${PublicPagesS3}",
          "UPLOADS_CLOUDFRONT_URL": "${UploadsCloudFrontUrl}",
          "UPLOADS_S3_BUCKET_NAME": "${UploadsS3}",
          "USER_POOL_CLIENT_ID": "${CognitoUserPoolClient.UserPoolClientId}",
          "USER_POOL_ID": "${CognitoUserPool.UserPoolId}"
        }
    DependsOn:
      - CognitoUserPool
      - CognitoUserPoolClient
      - SaveSettingsLambdaFunction

  # Send Email Lambda Resources

  SendDonationsReceiptEmailLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/SendDonationsReceiptEmail.zip
      Description: "Send a donations receipt email"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-SendDonationsReceiptEmail
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

  SendContactMessageEmailLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/SendContactMessageEmail.zip
      Description: "Send a contact message email"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-SendContactMessageEmail
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: !Ref DefaultLambdaFunctionTimeout

Outputs:

  AuthorizeUsers:
    Value: !Ref AuthorizeUsers

  CognitoCreateUserFunctionArn:
    Value: !GetAtt CognitoCreateUserFunction.Arn

  CognitoUserPoolId:
    Value: !GetAtt CognitoUserPool.UserPoolId

  CognitoUserPoolClientId:
    Value: !GetAtt CognitoUserPoolClient.UserPoolClientId