---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Custom resources for Givesource"
Parameters:

  StackName:
    Type: String

  LambdaRoleArn:
    Type: String

  HealthCheckUrl:
    Type: String

  DonationsTableStreamArn:
    Type: String

  DonorsTableStreamArn:
    Type: String

  NonprofitsTableStreamArn:
    Type: String

Resources:

  CloudSearchCreateDomainFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchCreateDomain.zip
      Description: "Create a CloudSearch domain"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CloudSearchCreateDomain
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30

  CloudSearchDomainWaitConditionLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchDomainWaitCondition.zip
      Description: "Wait for CloudSearch Domains to be ready"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CloudSearchDomainWaitCondition
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 120

  CloudSearchDescribeDomainFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchDescribeDomain.zip
      Description: "Describe CloudSearch domain"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
      FunctionName: !Sub |-
        ${StackName}-CloudSearchDescribeDomain
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30

  CloudSearchDonationsDomain:
    Type: Custom::CloudSearchDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchCreateDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Donations
    DependsOn: CloudSearchCreateDomainFunction

  CloudSearchDonorsDomain:
    Type: Custom::CloudSearchDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchCreateDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Donors
    DependsOn: CloudSearchCreateDomainFunction

  CloudSearchNonprofitsDomain:
    Type: Custom::CloudSearchDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchCreateDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Nonprofits
    DependsOn: CloudSearchCreateDomainFunction

  CloudSearchDomainWaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  CloudSearchDomainWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Count: 1
      Handle: !Ref CloudSearchDomainWaitConditionHandle
      Timeout: 2700
    DependsOn:
      - CloudSearchDomainWaitConditionHandle
      - CloudSearchDomainWaitConditionLambdaFunction

  CloudSearchDomainWaitConditionRecursive:
    Type: Custom::CloudSearchDomainWaitConditionRecursive
    Properties:
      ServiceToken: !GetAtt CloudSearchDomainWaitConditionLambdaFunction.Arn
      CallbackUrl: !Ref CloudSearchDomainWaitConditionHandle
      HealthCheckUrl: !Ref HealthCheckUrl
      ReportStatusToCloudFormation: true
    DependsOn: CloudSearchDomainWaitConditionLambdaFunction

  CloudSearchDescribeDonationsDomain:
    Type: Custom::CloudSearchDescribeDonationsDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchDescribeDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Donations
    DependsOn:
      - CloudSearchDescribeDomainFunction
      - CloudSearchDomainWaitCondition

  CloudSearchDescribeDonorsDomain:
    Type: Custom::CloudSearchDescribeDonorsDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchDescribeDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Donors
    DependsOn:
      - CloudSearchDescribeDomainFunction
      - CloudSearchDomainWaitCondition

  CloudSearchDescribeNonprofitsDomain:
    Type: Custom::CloudSearchDescribeNonprofitsDomain
    Properties:
      ServiceToken: !GetAtt CloudSearchDescribeDomainFunction.Arn
      DomainName: !Sub |-
        ${StackName}-Nonprofits
    DependsOn:
      - CloudSearchDescribeDomainFunction
      - CloudSearchDomainWaitCondition

  CloudSearchDonationsUploadDocumentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchUploadDocuments.zip
      Description: "Upload donation records to CloudSearch"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
          DOC_SERVICE_ENDPOINT: !GetAtt CloudSearchDescribeDonationsDomain.DocServiceEndpoint
      FunctionName: !Sub |-
        ${StackName}-CloudSearchDonationsUploadDocuments
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30
    DependsOn: CloudSearchDescribeDonationsDomain

  CloudSearchDonorsUploadDocumentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchUploadDocuments.zip
      Description: "Upload donor records to CloudSearch"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
          DOC_SERVICE_ENDPOINT: !GetAtt CloudSearchDescribeDonorsDomain.DocServiceEndpoint
      FunctionName: !Sub |-
        ${StackName}-CloudSearchDonorsUploadDocuments
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30
    DependsOn: CloudSearchDescribeDonorsDomain

  CloudSearchNonprofitsUploadDocumentsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Sub |-
          {{awsLambdaReleaseBucketPrefix}}-${AWS::Region}
        S3Key: fn/{{version}}/CloudSearchUploadDocuments.zip
      Description: "Upload nonprofit records to CloudSearch"
      Environment:
        Variables:
          AWS_STACK_NAME: !Ref StackName
          DOC_SERVICE_ENDPOINT: !GetAtt CloudSearchDescribeNonprofitsDomain.DocServiceEndpoint
      FunctionName: !Sub |-
        ${StackName}-CloudSearchNonprofitsUploadDocuments
      Handler: "index.handle"
      Role: !Ref LambdaRoleArn
      Runtime: "nodejs6.10"
      Timeout: 30
    DependsOn: CloudSearchDescribeNonprofitsDomain

  CloudSearchDonationsUploadDocumentsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      EventSourceArn: !Ref DonationsTableStreamArn
      FunctionName: !GetAtt CloudSearchDonationsUploadDocumentsFunction.Arn
      StartingPosition: TRIM_HORIZON
    DependsOn: CloudSearchDonationsUploadDocumentsFunction

  CloudSearchDonorsUploadDocumentsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      EventSourceArn: !Ref DonorsTableStreamArn
      FunctionName: !GetAtt CloudSearchDonorsUploadDocumentsFunction.Arn
      StartingPosition: TRIM_HORIZON
    DependsOn: CloudSearchDonorsUploadDocumentsFunction

  CloudSearchNonprofitsUploadDocumentsEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      EventSourceArn: !Ref NonprofitsTableStreamArn
      FunctionName: !GetAtt CloudSearchNonprofitsUploadDocumentsFunction.Arn
      StartingPosition: TRIM_HORIZON
    DependsOn: CloudSearchNonprofitsUploadDocumentsFunction

Outputs:

  CloudSearchDonationsDocServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeDonationsDomain.DocServiceEndpoint}

  CloudSearchDonationsSearchServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeDonationsDomain.SearchServiceEndpoint}

  CloudSearchDonorssDocServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeDonorsDomain.DocServiceEndpoint}

  CloudSearchDonorsSearchServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeDonorsDomain.SearchServiceEndpoint}

  CloudSearchNonprofitsDocServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeNonprofitsDomain.DocServiceEndpoint}

  CloudSearchNonprofitsSearchServiceEndpoint:
    Value: !Sub |-
      ${CloudSearchDescribeNonprofitsDomain.SearchServiceEndpoint}